//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail1
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public int BillingCityId { get; set; }
        public int ShippingCityId { get; set; }
        public string Notes { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOndate { get; set; }
        public string BillingTown { get; set; }
        public string BillingBlock { get; set; }
        public string BillingStreet { get; set; }
        public int BillingHouseNo { get; set; }
        public int BillingApartmentNo { get; set; }
        public Nullable<int> BillingPaciNo { get; set; }
        public string ShippingTown { get; set; }
        public string ShippingBlock { get; set; }
        public string ShippingStreet { get; set; }
        public int ShippingHouseNo { get; set; }
        public int ShippingApartmentNo { get; set; }
        public Nullable<int> ShippingPaciNo { get; set; }
        public string ShippingNumber { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
