

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using DataAccess.Modals;
using Entities;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class GeneralEntities : DbContext
{
    public GeneralEntities()
        : base("name=GeneralEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ContactU> ContactUs { get; set; }

    public virtual DbSet<SubscribedEmail> SubscribedEmails { get; set; }

    public virtual DbSet<FAQ> FAQs { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<SubCategory> SubCategories { get; set; }

    public virtual DbSet<Color> Colors { get; set; }

    public virtual DbSet<Size> Sizes { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<Charity> Charities { get; set; }

    public virtual DbSet<AboutU> AboutUs { get; set; }

    public virtual DbSet<ContactUsChannel> ContactUsChannels { get; set; }

    public virtual DbSet<ContactUsPeopleAsk> ContactUsPeopleAsks { get; set; }

    public virtual DbSet<PrivacyPolicy> PrivacyPolicies { get; set; }

    public virtual DbSet<TermAndCondition> TermAndConditions { get; set; }

    public virtual DbSet<Slaughterhouse> Slaughterhouses { get; set; }

    public virtual DbSet<Status1> Status1 { get; set; }

    public virtual DbSet<AppVersion> AppVersions { get; set; }

    public virtual DbSet<PromoCode> PromoCodes { get; set; }

    public virtual DbSet<ProductPurpos> ProductPurposes { get; set; }

    public virtual DbSet<CancellationPolicy> CancellationPolicies { get; set; }

    public virtual DbSet<OurService> OurServices { get; set; }


    public virtual ObjectResult<GetCountriesList_Result> GetCountriesList(string txt, Nullable<int> isActive, Nullable<int> inActive, Nullable<int> start, Nullable<int> end)
    {

        var txtParameter = txt != null ?
            new ObjectParameter("txt", txt) :
            new ObjectParameter("txt", typeof(string));


        var isActiveParameter = isActive.HasValue ?
            new ObjectParameter("IsActive", isActive) :
            new ObjectParameter("IsActive", typeof(int));


        var inActiveParameter = inActive.HasValue ?
            new ObjectParameter("InActive", inActive) :
            new ObjectParameter("InActive", typeof(int));


        var startParameter = start.HasValue ?
            new ObjectParameter("Start", start) :
            new ObjectParameter("Start", typeof(int));


        var endParameter = end.HasValue ?
            new ObjectParameter("End", end) :
            new ObjectParameter("End", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountriesList_Result>("GetCountriesList", txtParameter, isActiveParameter, inActiveParameter, startParameter, endParameter);
    }

}

