//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public int BatchId { get; set; }
        public int Order_person_id { get; set; }
        public int OrderId { get; set; }
        public string ProductName { get; set; }
        public string Shareholder { get; set; }
        public bool IsSlaughtered { get; set; }
        public bool IsRecorded { get; set; }
        public bool IsDistributed { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> LastModById { get; set; }
        public Nullable<System.DateTime> LastModOnDate { get; set; }
        public string URL { get; set; }
        public string AddressDetails { get; set; }
        public Nullable<int> ProductPurposeId { get; set; }
        public string PurposeName { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Order Order { get; set; }
    }
}
