//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int BatchId { get; set; }
        public string Message { get; set; }
        public bool IsSeen { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> SlaughterId { get; set; }
        public Nullable<int> CharityId { get; set; }
    }
}
