//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.PersonShippingAddresses = new HashSet<PersonShippingAddress>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public string FullName { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> CharityId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string AddressDetails { get; set; }
        public Nullable<int> ProductPurposeId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Products1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonShippingAddress> PersonShippingAddresses { get; set; }
    }
}
