//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonShippingAddress
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int CityId { get; set; }
        public string Town { get; set; }
        public string Block { get; set; }
        public string Street { get; set; }
        public Nullable<int> HouseNo { get; set; }
        public Nullable<int> ApartmentNo { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public string ContactNumber { get; set; }
        public string CuttingNotes { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
