//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price1
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public double TotalPriceUsd { get; set; }
        public double TotalPriceKwd { get; set; }
        public int ShippingPriceKwd { get; set; }
        public int ShiipingPriceUsd { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public string PromoCode { get; set; }
        public Nullable<double> CodeValue { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
