//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public double Usd { get; set; }
        public double Kwd { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> LastModById { get; set; }
        public Nullable<System.DateTime> LastModOnDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
