

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using DataAccess.Modals;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class productsEntities : DbContext
{
    public productsEntities()
        : base("name=productsEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Image> Images { get; set; }

    public virtual DbSet<Price> Prices { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Stock> Stocks { get; set; }

    public virtual DbSet<Wishlist> Wishlists { get; set; }

    public virtual DbSet<Detail> Details { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Detail1> Detail1 { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Price1> Price1 { get; set; }

    public virtual DbSet<Product1> Product1 { get; set; }

    public virtual DbSet<Track> Tracks { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<Person> Persons { get; set; }

    public virtual DbSet<Charity> Charities { get; set; }

    public virtual DbSet<Batch> Batches { get; set; }

    public virtual DbSet<Track1> Track1 { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<ProductPurpos> ProductPurposes { get; set; }

    public virtual DbSet<PersonShippingAddress> PersonShippingAddresses { get; set; }

    public virtual DbSet<City> Cities { get; set; }


    public virtual ObjectResult<GetProductsList_Result> GetProductsList(string brands, Nullable<double> min, Nullable<double> max, string categories, string sort, Nullable<int> start, Nullable<int> end, string currency, string txt, string subCategories, string userToken, string newArrival, string onSale, string country)
    {

        var brandsParameter = brands != null ?
            new ObjectParameter("Brands", brands) :
            new ObjectParameter("Brands", typeof(string));


        var minParameter = min.HasValue ?
            new ObjectParameter("Min", min) :
            new ObjectParameter("Min", typeof(double));


        var maxParameter = max.HasValue ?
            new ObjectParameter("Max", max) :
            new ObjectParameter("Max", typeof(double));


        var categoriesParameter = categories != null ?
            new ObjectParameter("Categories", categories) :
            new ObjectParameter("Categories", typeof(string));


        var sortParameter = sort != null ?
            new ObjectParameter("Sort", sort) :
            new ObjectParameter("Sort", typeof(string));


        var startParameter = start.HasValue ?
            new ObjectParameter("Start", start) :
            new ObjectParameter("Start", typeof(int));


        var endParameter = end.HasValue ?
            new ObjectParameter("End", end) :
            new ObjectParameter("End", typeof(int));


        var currencyParameter = currency != null ?
            new ObjectParameter("Currency", currency) :
            new ObjectParameter("Currency", typeof(string));


        var txtParameter = txt != null ?
            new ObjectParameter("txt", txt) :
            new ObjectParameter("txt", typeof(string));


        var subCategoriesParameter = subCategories != null ?
            new ObjectParameter("SubCategories", subCategories) :
            new ObjectParameter("SubCategories", typeof(string));


        var userTokenParameter = userToken != null ?
            new ObjectParameter("UserToken", userToken) :
            new ObjectParameter("UserToken", typeof(string));


        var newArrivalParameter = newArrival != null ?
            new ObjectParameter("NewArrival", newArrival) :
            new ObjectParameter("NewArrival", typeof(string));


        var onSaleParameter = onSale != null ?
            new ObjectParameter("OnSale", onSale) :
            new ObjectParameter("OnSale", typeof(string));


        var countryParameter = country != null ?
            new ObjectParameter("Country", country) :
            new ObjectParameter("Country", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsList_Result>("GetProductsList", brandsParameter, minParameter, maxParameter, categoriesParameter, sortParameter, startParameter, endParameter, currencyParameter, txtParameter, subCategoriesParameter, userTokenParameter, newArrivalParameter, onSaleParameter, countryParameter);
    }


    public virtual ObjectResult<GetProductsList_Result> GetAdminProducts(string brands, Nullable<double> min, Nullable<double> max, string categories, string sort, Nullable<int> start, Nullable<int> end, string currency, string txt, string subCategories, string userToken, string newArrival, string onSale)
    {

        var brandsParameter = brands != null ?
            new ObjectParameter("Brands", brands) :
            new ObjectParameter("Brands", typeof(string));


        var minParameter = min.HasValue ?
            new ObjectParameter("Min", min) :
            new ObjectParameter("Min", typeof(double));


        var maxParameter = max.HasValue ?
            new ObjectParameter("Max", max) :
            new ObjectParameter("Max", typeof(double));


        var categoriesParameter = categories != null ?
            new ObjectParameter("Categories", categories) :
            new ObjectParameter("Categories", typeof(string));


        var sortParameter = sort != null ?
            new ObjectParameter("Sort", sort) :
            new ObjectParameter("Sort", typeof(string));


        var startParameter = start.HasValue ?
            new ObjectParameter("Start", start) :
            new ObjectParameter("Start", typeof(int));


        var endParameter = end.HasValue ?
            new ObjectParameter("End", end) :
            new ObjectParameter("End", typeof(int));


        var currencyParameter = currency != null ?
            new ObjectParameter("Currency", currency) :
            new ObjectParameter("Currency", typeof(string));


        var txtParameter = txt != null ?
            new ObjectParameter("txt", txt) :
            new ObjectParameter("txt", typeof(string));


        var subCategoriesParameter = subCategories != null ?
            new ObjectParameter("SubCategories", subCategories) :
            new ObjectParameter("SubCategories", typeof(string));


        var userTokenParameter = userToken != null ?
            new ObjectParameter("UserToken", userToken) :
            new ObjectParameter("UserToken", typeof(string));


        var newArrivalParameter = newArrival != null ?
            new ObjectParameter("NewArrival", newArrival) :
            new ObjectParameter("NewArrival", typeof(string));


        var onSaleParameter = onSale != null ?
            new ObjectParameter("OnSale", onSale) :
            new ObjectParameter("OnSale", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsList_Result>("GetAdminProducts", brandsParameter, minParameter, maxParameter, categoriesParameter, sortParameter, startParameter, endParameter, currencyParameter, txtParameter, subCategoriesParameter, userTokenParameter, newArrivalParameter, onSaleParameter);
    }


    public virtual ObjectResult<GetWishlist_Result> GetWishlist(string userToken)
    {

        var userTokenParameter = userToken != null ?
            new ObjectParameter("UserToken", userToken) :
            new ObjectParameter("UserToken", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWishlist_Result>("GetWishlist", userTokenParameter);
    }


    public virtual ObjectResult<GetHomePageLists_Result> GetHomePageLists(string userToken)
    {

        var userTokenParameter = userToken != null ?
            new ObjectParameter("UserToken", userToken) :
            new ObjectParameter("UserToken", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHomePageLists_Result>("GetHomePageLists", userTokenParameter);
    }


    public virtual ObjectResult<GetCartItems_Result> GetCartItems(string tokens)
    {

        var tokensParameter = tokens != null ?
            new ObjectParameter("Tokens", tokens) :
            new ObjectParameter("Tokens", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartItems_Result>("GetCartItems", tokensParameter);
    }


    public virtual int SubmitOrder(string userToken, string items, string firstName, string lastName, string mobile, string email, Nullable<int> billingCityId, string billingTown, string billingBlock, string billingStreet, Nullable<int> billingHouse, Nullable<int> billingApartment, Nullable<int> billingPaci, Nullable<int> shippingCityId, string shippingTown, string shippingBlock, string shippingStreet, Nullable<int> shippingHouse, Nullable<int> shippingApartment, Nullable<int> shippingPaci, string notes, Nullable<int> statusId, ObjectParameter orderId, string promoCode, Nullable<double> codeValue)
    {

        var userTokenParameter = userToken != null ?
            new ObjectParameter("UserToken", userToken) :
            new ObjectParameter("UserToken", typeof(string));


        var itemsParameter = items != null ?
            new ObjectParameter("Items", items) :
            new ObjectParameter("Items", typeof(string));


        var firstNameParameter = firstName != null ?
            new ObjectParameter("FirstName", firstName) :
            new ObjectParameter("FirstName", typeof(string));


        var lastNameParameter = lastName != null ?
            new ObjectParameter("LastName", lastName) :
            new ObjectParameter("LastName", typeof(string));


        var mobileParameter = mobile != null ?
            new ObjectParameter("Mobile", mobile) :
            new ObjectParameter("Mobile", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        var billingCityIdParameter = billingCityId.HasValue ?
            new ObjectParameter("BillingCityId", billingCityId) :
            new ObjectParameter("BillingCityId", typeof(int));


        var billingTownParameter = billingTown != null ?
            new ObjectParameter("BillingTown", billingTown) :
            new ObjectParameter("BillingTown", typeof(string));


        var billingBlockParameter = billingBlock != null ?
            new ObjectParameter("BillingBlock", billingBlock) :
            new ObjectParameter("BillingBlock", typeof(string));


        var billingStreetParameter = billingStreet != null ?
            new ObjectParameter("BillingStreet", billingStreet) :
            new ObjectParameter("BillingStreet", typeof(string));


        var billingHouseParameter = billingHouse.HasValue ?
            new ObjectParameter("BillingHouse", billingHouse) :
            new ObjectParameter("BillingHouse", typeof(int));


        var billingApartmentParameter = billingApartment.HasValue ?
            new ObjectParameter("BillingApartment", billingApartment) :
            new ObjectParameter("BillingApartment", typeof(int));


        var billingPaciParameter = billingPaci.HasValue ?
            new ObjectParameter("BillingPaci", billingPaci) :
            new ObjectParameter("BillingPaci", typeof(int));


        var shippingCityIdParameter = shippingCityId.HasValue ?
            new ObjectParameter("ShippingCityId", shippingCityId) :
            new ObjectParameter("ShippingCityId", typeof(int));


        var shippingTownParameter = shippingTown != null ?
            new ObjectParameter("ShippingTown", shippingTown) :
            new ObjectParameter("ShippingTown", typeof(string));


        var shippingBlockParameter = shippingBlock != null ?
            new ObjectParameter("ShippingBlock", shippingBlock) :
            new ObjectParameter("ShippingBlock", typeof(string));


        var shippingStreetParameter = shippingStreet != null ?
            new ObjectParameter("ShippingStreet", shippingStreet) :
            new ObjectParameter("ShippingStreet", typeof(string));


        var shippingHouseParameter = shippingHouse.HasValue ?
            new ObjectParameter("ShippingHouse", shippingHouse) :
            new ObjectParameter("ShippingHouse", typeof(int));


        var shippingApartmentParameter = shippingApartment.HasValue ?
            new ObjectParameter("ShippingApartment", shippingApartment) :
            new ObjectParameter("ShippingApartment", typeof(int));


        var shippingPaciParameter = shippingPaci.HasValue ?
            new ObjectParameter("ShippingPaci", shippingPaci) :
            new ObjectParameter("ShippingPaci", typeof(int));


        var notesParameter = notes != null ?
            new ObjectParameter("Notes", notes) :
            new ObjectParameter("Notes", typeof(string));


        var statusIdParameter = statusId.HasValue ?
            new ObjectParameter("StatusId", statusId) :
            new ObjectParameter("StatusId", typeof(int));


        var promoCodeParameter = promoCode != null ?
            new ObjectParameter("PromoCode", promoCode) :
            new ObjectParameter("PromoCode", typeof(string));


        var codeValueParameter = codeValue.HasValue ?
            new ObjectParameter("CodeValue", codeValue) :
            new ObjectParameter("CodeValue", typeof(double));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubmitOrder", userTokenParameter, itemsParameter, firstNameParameter, lastNameParameter, mobileParameter, emailParameter, billingCityIdParameter, billingTownParameter, billingBlockParameter, billingStreetParameter, billingHouseParameter, billingApartmentParameter, billingPaciParameter, shippingCityIdParameter, shippingTownParameter, shippingBlockParameter, shippingStreetParameter, shippingHouseParameter, shippingApartmentParameter, shippingPaciParameter, notesParameter, statusIdParameter, orderId, promoCodeParameter, codeValueParameter);
    }


    public virtual ObjectResult<GetAdminOrders_Result> GetAdminOrders(string statuses, Nullable<int> orderId, Nullable<int> hasDate, Nullable<System.DateTime> date, Nullable<int> start, Nullable<int> end, string promoCode)
    {

        var statusesParameter = statuses != null ?
            new ObjectParameter("Statuses", statuses) :
            new ObjectParameter("Statuses", typeof(string));


        var orderIdParameter = orderId.HasValue ?
            new ObjectParameter("OrderId", orderId) :
            new ObjectParameter("OrderId", typeof(int));


        var hasDateParameter = hasDate.HasValue ?
            new ObjectParameter("HasDate", hasDate) :
            new ObjectParameter("HasDate", typeof(int));


        var dateParameter = date.HasValue ?
            new ObjectParameter("Date", date) :
            new ObjectParameter("Date", typeof(System.DateTime));


        var startParameter = start.HasValue ?
            new ObjectParameter("Start", start) :
            new ObjectParameter("Start", typeof(int));


        var endParameter = end.HasValue ?
            new ObjectParameter("End", end) :
            new ObjectParameter("End", typeof(int));


        var promoCodeParameter = promoCode != null ?
            new ObjectParameter("PromoCode", promoCode) :
            new ObjectParameter("PromoCode", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdminOrders_Result>("GetAdminOrders", statusesParameter, orderIdParameter, hasDateParameter, dateParameter, startParameter, endParameter, promoCodeParameter);
    }


    public virtual ObjectResult<GetAvailableBatchProductsList_Result> GetAvailableBatchProductsList(string brands, string categories, Nullable<int> start, Nullable<int> end, string subCategories, string userToken, Nullable<int> charityId, Nullable<int> delivery)
    {

        var brandsParameter = brands != null ?
            new ObjectParameter("Brands", brands) :
            new ObjectParameter("Brands", typeof(string));


        var categoriesParameter = categories != null ?
            new ObjectParameter("Categories", categories) :
            new ObjectParameter("Categories", typeof(string));


        var startParameter = start.HasValue ?
            new ObjectParameter("Start", start) :
            new ObjectParameter("Start", typeof(int));


        var endParameter = end.HasValue ?
            new ObjectParameter("End", end) :
            new ObjectParameter("End", typeof(int));


        var subCategoriesParameter = subCategories != null ?
            new ObjectParameter("SubCategories", subCategories) :
            new ObjectParameter("SubCategories", typeof(string));


        var userTokenParameter = userToken != null ?
            new ObjectParameter("UserToken", userToken) :
            new ObjectParameter("UserToken", typeof(string));


        var charityIdParameter = charityId.HasValue ?
            new ObjectParameter("CharityId", charityId) :
            new ObjectParameter("CharityId", typeof(int));


        var deliveryParameter = delivery.HasValue ?
            new ObjectParameter("Delivery", delivery) :
            new ObjectParameter("Delivery", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAvailableBatchProductsList_Result>("GetAvailableBatchProductsList", brandsParameter, categoriesParameter, startParameter, endParameter, subCategoriesParameter, userTokenParameter, charityIdParameter, deliveryParameter);
    }


    public virtual ObjectResult<GenerateBatch_Result> GenerateBatch(string brands, string categories, string subCategories, string userToken, Nullable<int> charityId, Nullable<int> quantity, Nullable<int> slaughterhouses, Nullable<int> delivery)
    {

        var brandsParameter = brands != null ?
            new ObjectParameter("Brands", brands) :
            new ObjectParameter("Brands", typeof(string));


        var categoriesParameter = categories != null ?
            new ObjectParameter("Categories", categories) :
            new ObjectParameter("Categories", typeof(string));


        var subCategoriesParameter = subCategories != null ?
            new ObjectParameter("SubCategories", subCategories) :
            new ObjectParameter("SubCategories", typeof(string));


        var userTokenParameter = userToken != null ?
            new ObjectParameter("UserToken", userToken) :
            new ObjectParameter("UserToken", typeof(string));


        var charityIdParameter = charityId.HasValue ?
            new ObjectParameter("CharityId", charityId) :
            new ObjectParameter("CharityId", typeof(int));


        var quantityParameter = quantity.HasValue ?
            new ObjectParameter("Quantity", quantity) :
            new ObjectParameter("Quantity", typeof(int));


        var slaughterhousesParameter = slaughterhouses.HasValue ?
            new ObjectParameter("Slaughterhouses", slaughterhouses) :
            new ObjectParameter("Slaughterhouses", typeof(int));


        var deliveryParameter = delivery.HasValue ?
            new ObjectParameter("Delivery", delivery) :
            new ObjectParameter("Delivery", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateBatch_Result>("GenerateBatch", brandsParameter, categoriesParameter, subCategoriesParameter, userTokenParameter, charityIdParameter, quantityParameter, slaughterhousesParameter, deliveryParameter);
    }


    public virtual ObjectResult<GetAdminBatches_Result> GetAdminBatches(string statuses, Nullable<int> batchId, Nullable<int> orderId, Nullable<int> slaughterhouseId, Nullable<int> charityId, Nullable<int> hasDate, Nullable<System.DateTime> date, Nullable<int> start, Nullable<int> end)
    {

        var statusesParameter = statuses != null ?
            new ObjectParameter("Statuses", statuses) :
            new ObjectParameter("Statuses", typeof(string));


        var batchIdParameter = batchId.HasValue ?
            new ObjectParameter("BatchId", batchId) :
            new ObjectParameter("BatchId", typeof(int));


        var orderIdParameter = orderId.HasValue ?
            new ObjectParameter("OrderId", orderId) :
            new ObjectParameter("OrderId", typeof(int));


        var slaughterhouseIdParameter = slaughterhouseId.HasValue ?
            new ObjectParameter("SlaughterhouseId", slaughterhouseId) :
            new ObjectParameter("SlaughterhouseId", typeof(int));


        var charityIdParameter = charityId.HasValue ?
            new ObjectParameter("CharityId", charityId) :
            new ObjectParameter("CharityId", typeof(int));


        var hasDateParameter = hasDate.HasValue ?
            new ObjectParameter("HasDate", hasDate) :
            new ObjectParameter("HasDate", typeof(int));


        var dateParameter = date.HasValue ?
            new ObjectParameter("Date", date) :
            new ObjectParameter("Date", typeof(System.DateTime));


        var startParameter = start.HasValue ?
            new ObjectParameter("Start", start) :
            new ObjectParameter("Start", typeof(int));


        var endParameter = end.HasValue ?
            new ObjectParameter("End", end) :
            new ObjectParameter("End", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdminBatches_Result>("GetAdminBatches", statusesParameter, batchIdParameter, orderIdParameter, slaughterhouseIdParameter, charityIdParameter, hasDateParameter, dateParameter, startParameter, endParameter);
    }


    public virtual ObjectResult<GetAdminBatches1_Result> GetAdminBatches1(string statuses, Nullable<int> batchId, Nullable<int> orderId, Nullable<int> slaughterhouseId, Nullable<int> charityId, Nullable<int> hasDate, Nullable<System.DateTime> date, Nullable<int> start, Nullable<int> end)
    {

        var statusesParameter = statuses != null ?
            new ObjectParameter("Statuses", statuses) :
            new ObjectParameter("Statuses", typeof(string));


        var batchIdParameter = batchId.HasValue ?
            new ObjectParameter("BatchId", batchId) :
            new ObjectParameter("BatchId", typeof(int));


        var orderIdParameter = orderId.HasValue ?
            new ObjectParameter("OrderId", orderId) :
            new ObjectParameter("OrderId", typeof(int));


        var slaughterhouseIdParameter = slaughterhouseId.HasValue ?
            new ObjectParameter("SlaughterhouseId", slaughterhouseId) :
            new ObjectParameter("SlaughterhouseId", typeof(int));


        var charityIdParameter = charityId.HasValue ?
            new ObjectParameter("CharityId", charityId) :
            new ObjectParameter("CharityId", typeof(int));


        var hasDateParameter = hasDate.HasValue ?
            new ObjectParameter("HasDate", hasDate) :
            new ObjectParameter("HasDate", typeof(int));


        var dateParameter = date.HasValue ?
            new ObjectParameter("Date", date) :
            new ObjectParameter("Date", typeof(System.DateTime));


        var startParameter = start.HasValue ?
            new ObjectParameter("Start", start) :
            new ObjectParameter("Start", typeof(int));


        var endParameter = end.HasValue ?
            new ObjectParameter("End", end) :
            new ObjectParameter("End", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdminBatches1_Result>("GetAdminBatches1", statusesParameter, batchIdParameter, orderIdParameter, slaughterhouseIdParameter, charityIdParameter, hasDateParameter, dateParameter, startParameter, endParameter);
    }


    public virtual ObjectResult<GetBatchItems_Result> GetBatchItems(Nullable<int> batchId, Nullable<int> start, Nullable<int> end)
    {

        var batchIdParameter = batchId.HasValue ?
            new ObjectParameter("BatchId", batchId) :
            new ObjectParameter("BatchId", typeof(int));


        var startParameter = start.HasValue ?
            new ObjectParameter("Start", start) :
            new ObjectParameter("Start", typeof(int));


        var endParameter = end.HasValue ?
            new ObjectParameter("End", end) :
            new ObjectParameter("End", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBatchItems_Result>("GetBatchItems", batchIdParameter, startParameter, endParameter);
    }


    public virtual ObjectResult<GetCharityBatchesCounts_Result> GetCharityBatchesCounts(Nullable<int> charityId)
    {

        var charityIdParameter = charityId.HasValue ?
            new ObjectParameter("CharityId", charityId) :
            new ObjectParameter("CharityId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCharityBatchesCounts_Result>("GetCharityBatchesCounts", charityIdParameter);
    }


    public virtual ObjectResult<GetSlaughterhouseBatchesCounts_Result> GetSlaughterhouseBatchesCounts(Nullable<int> slaughterhouseId)
    {

        var slaughterhouseIdParameter = slaughterhouseId.HasValue ?
            new ObjectParameter("SlaughterhouseId", slaughterhouseId) :
            new ObjectParameter("SlaughterhouseId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSlaughterhouseBatchesCounts_Result>("GetSlaughterhouseBatchesCounts", slaughterhouseIdParameter);
    }


    public virtual ObjectResult<GetProductDetails_Result> GetProductDetails(string token, string userToken)
    {

        var tokenParameter = token != null ?
            new ObjectParameter("Token", token) :
            new ObjectParameter("Token", typeof(string));


        var userTokenParameter = userToken != null ?
            new ObjectParameter("UserToken", userToken) :
            new ObjectParameter("UserToken", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDetails_Result>("GetProductDetails", tokenParameter, userTokenParameter);
    }

}

