//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoCode
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Discount { get; set; }
        public int FixValue { get; set; }
        public int MinInvoice { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedById { get; set; }
        public Nullable<int> LastModByid { get; set; }
        public Nullable<System.DateTime> LastModOnDate { get; set; }
    }
}
