//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string Result { get; set; }
        public string Ref { get; set; }
        public string TrackId { get; set; }
        public string TransId { get; set; }
        public string PaymentId { get; set; }
        public string Date { get; set; }
        public string Amount { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
