

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using DataAccess.Modals;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class UsersEntities : DbContext
{
    public UsersEntities()
        : base("name=UsersEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<ResetPasswordToken> ResetPasswordTokens { get; set; }

    public virtual DbSet<UsersDetail> UsersDetails { get; set; }

    public virtual DbSet<BillingAddress> BillingAddresses { get; set; }

    public virtual DbSet<ShippingAddress> ShippingAddresses { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<ResetPasswordVerifyCode> ResetPasswordVerifyCodes { get; set; }

    public virtual DbSet<AuthToken> AuthTokens { get; set; }


    public virtual ObjectResult<GetUsersList_Result> GetUsersList(string txt, Nullable<int> isActive, Nullable<int> inActive, Nullable<int> isAdmin, Nullable<int> start, Nullable<int> end)
    {

        var txtParameter = txt != null ?
            new ObjectParameter("txt", txt) :
            new ObjectParameter("txt", typeof(string));


        var isActiveParameter = isActive.HasValue ?
            new ObjectParameter("IsActive", isActive) :
            new ObjectParameter("IsActive", typeof(int));


        var inActiveParameter = inActive.HasValue ?
            new ObjectParameter("InActive", inActive) :
            new ObjectParameter("InActive", typeof(int));


        var isAdminParameter = isAdmin.HasValue ?
            new ObjectParameter("IsAdmin", isAdmin) :
            new ObjectParameter("IsAdmin", typeof(int));


        var startParameter = start.HasValue ?
            new ObjectParameter("Start", start) :
            new ObjectParameter("Start", typeof(int));


        var endParameter = end.HasValue ?
            new ObjectParameter("End", end) :
            new ObjectParameter("End", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsersList_Result>("GetUsersList", txtParameter, isActiveParameter, inActiveParameter, isAdminParameter, startParameter, endParameter);
    }

}

